### ISSUE TITLE
Variable can be declared and initialized within the for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-Sandeep-raj#1]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-Sandeep-raj/blob/3c5f0e313c06a87d79fa96362ac2afb95b94ac12/reverse-using-iterators.js#L3

**Comment by Sandeep-raj** [comment]
Variables are declared and initialized inside the loop
