### ISSUE TITLE
Use es6 Arrow Function without using return keyword

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/reverse-string-js-problem-Sandeep-raj#2]
https://github.com/sro-boeing-wave-2/reverse-string-js-problem-Sandeep-raj/blob/3c5f0e313c06a87d79fa96362ac2afb95b94ac12/reverse-using-built-in-function.js#L5-L8

**Comment by Sandeep-raj** [comment]
Used arrow function to return the value.
